on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: test
jobs:
  build-and-test:
    name: my-job
    runs-on: ubuntu-latest
    env:
      DB_FILE_NAME: test.db
      SESSION_SECRET: secret
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # run any `bun` or `bunx` command
      - run: bun install --frozen-lockfile
      - run: bun run lint
      - run: bun run format-check
      - run: bun run test
      - run: bun run build
